export enum EActionTypes {

    USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE',

    USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE',

    MESSAGE_SEND_REQUEST = 'MESSAGE_SEND_REQUEST',

    MESSAGE_LIST_REQUEST = 'MESSAGE_LIST_REQUEST',
    MESSAGE_LIST_UPDATE = 'MESSAGE_LIST_UPDATE',

    NOTIFICATION_UPDATE  = 'NOTIFICATION_UPDATE'
}
